const t=JSON.parse('{"key":"v-5add3977","path":"/blogs/Java/basic/basic009.html","title":"Java的异常机制","lang":"en-US","frontmatter":{"title":"Java的异常机制","date":"2022/04/10","tags":["年份2022"]},"headers":[{"level":2,"title":"概述","slug":"概述","link":"#概述","children":[]},{"level":2,"title":"注意点","slug":"注意点","link":"#注意点","children":[{"level":3,"title":"如何使用 try-with-resources 代替try-catch-finally？","slug":"如何使用-try-with-resources-代替try-catch-finally","link":"#如何使用-try-with-resources-代替try-catch-finally","children":[]}]}],"git":{},"filePathRelative":"blogs/Java/basic/basic009.md"}');export{t as data};
